"use client";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { Play, Pause, Check, MapPin, Send, ArrowLeft, RotateCcw } from "lucide-react";
import { startTaskAction, completeTaskAction, submitEvidenceAction, uploadEvidenceAction } from "@/presentation/actions/task-actions";
import { pauseTaskAction, resumeTaskAction, reportImpedimentAction } from "@/presentation/actions/management-task-actions";
import { PageHeader, StatusBadge, PriorityBadge, Modal } from "../shared";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";
import { Field, FieldLabel, FieldGroup } from "@/components/ui/field";
import { Badge } from "@/components/ui/badge";
import { Spinner } from "@/components/ui/spinner";
type Evidence = { id: string; type: string; required: boolean; minQuantity: number; executionStage?: string; submissions: { id: string; validationStatus: string; attemptNumber: number; value: string | null; createdAt: string; storageKey?: string | null }[] };
interface TaskDetailClientProps { task: { id: string; title: string; description: string | null; instructions: string | null; status: string; priority: string; deadlineAt: Date | null; locationName: string | null; scheduledDate?: Date | null; requiresApproval?: boolean; correctionRequested?: boolean; dependencies: { id: string; type: string; logic: string; dependsOnTask: { id: string; title: string; status: string } }[]; occurrences: { id: string; type: string; category: string; reason: string; severity: string; createdAt: string }[]; evidenceRequirements: Evidence[] } }
const labels: Record<string, string> = { PHOTO: "Foto", VIDEO: "Vídeo", FILE: "Arquivo", TEXT: "Texto", NUMBER: "Medição numérica", SIGNATURE: "Assinatura", LOCATION: "Localização" };

function EvidenceForm({ taskId, requirement: req, disabled, onResult }: { taskId: string; requirement: Evidence; disabled: boolean; onResult: (error?: string) => void }) {
  const [busy, setBusy] = useState(false), [value, setValue] = useState(""), [file, setFile] = useState<File | null>(null), [signed, setSigned] = useState(false);
  const canvas = useRef<HTMLCanvasElement>(null), drawing = useRef(false);
  const valid = req.submissions.filter(s => s.validationStatus === "VALID"), failures = req.submissions.filter(s => s.validationStatus === "REJECTED").length;
  const done = valid.length >= req.minQuantity;
  async function submit(e: React.FormEvent) {
    e.preventDefault(); setBusy(true);
    try {
      let selected = file;
      if (req.type === "SIGNATURE") { if (!signed || !canvas.current) { onResult("Desenhe a assinatura antes de enviar."); return; } const blob = await new Promise<Blob | null>(resolve => canvas.current!.toBlob(resolve, "image/png")); if (blob) selected = new File([blob], "assinatura.png", { type: "image/png" }); }
      if (["PHOTO", "VIDEO", "FILE", "SIGNATURE"].includes(req.type)) { if (!selected) { onResult("Selecione um arquivo antes de enviar."); return; } const form = new FormData(); form.set("taskId", taskId); form.set("requirementId", req.id); form.set("file", selected); const r = await uploadEvidenceAction(form); onResult(r.error); }
      else { const r = await submitEvidenceAction(taskId, req.id, value); onResult(r.error); }
    } catch { onResult("Não foi possível enviar. Verifique a conexão e tente novamente."); } finally { setBusy(false); }
  }
  async function gps() {
    if (!navigator.geolocation) { onResult("Este dispositivo não oferece localização."); return; }
    setBusy(true);
    navigator.geolocation.getCurrentPosition(p => { setValue(JSON.stringify({ latitude: p.coords.latitude, longitude: p.coords.longitude, accuracy: p.coords.accuracy })); setBusy(false); }, () => { onResult("Não foi possível obter a localização. Permita o acesso ao GPS e tente novamente."); setBusy(false); }, { enableHighAccuracy: true, timeout: 15000, maximumAge: 0 });
  }
  return <div className="evidence-form"><div className="flex flex-wrap justify-between gap-2 items-center"><h3 className="font-semibold">{labels[req.type] || req.type}</h3><Badge variant={done ? "secondary" : "outline"}>{done ? "Registrada" : req.required ? "Obrigatória" : "Opcional"}</Badge></div>{valid.map(s => <p className="text-label text-muted-foreground break-words" key={s.id}>{s.storageKey ? <a className="underline" href={`/api/evidence/${s.id}`}>Baixar {s.value || "evidência"}</a> : s.value}</p>)}{failures > 0 && <p className="text-caption text-muted-foreground">{failures} {failures === 1 ? "tentativa inválida" : "tentativas inválidas"}.{failures >= 3 ? " Você pode continuar com ressalva. A gestão foi avisada." : " Corrija o envio para continuar."}</p>}
    {!done && !disabled && <form onSubmit={submit} className="flex flex-col gap-3">
      {["PHOTO", "VIDEO", "FILE"].includes(req.type) && <Field><FieldLabel htmlFor={`file-${req.id}`}>Escolha {req.type === "PHOTO" ? "uma foto" : req.type === "VIDEO" ? "um vídeo" : "um arquivo"}</FieldLabel><Input id={`file-${req.id}`} type="file" accept={req.type === "PHOTO" ? "image/jpeg,image/png,image/webp" : req.type === "VIDEO" ? "video/mp4" : "image/jpeg,image/png,image/webp,application/pdf,video/mp4"} capture={req.type === "PHOTO" ? "environment" : undefined} onChange={e => setFile(e.target.files?.[0] ?? null)} required /><p className="text-caption text-muted-foreground">Até 10 MB. {req.type === "VIDEO" ? "Formato MP4." : "JPG, PNG, WebP" + (req.type === "FILE" ? ", PDF ou MP4." : ".")}</p></Field>}
      {["TEXT", "NUMBER"].includes(req.type) && <Field><FieldLabel htmlFor={`value-${req.id}`}>{req.type === "TEXT" ? "Descreva o resultado" : "Valor medido"}</FieldLabel>{req.type === "TEXT" ? <Textarea id={`value-${req.id}`} value={value} onChange={e => setValue(e.target.value)} required /> : <Input id={`value-${req.id}`} type="number" step="any" value={value} onChange={e => setValue(e.target.value)} required />}</Field>}
      {req.type === "LOCATION" && <><Button type="button" variant="outline" disabled={busy} onClick={gps}><MapPin data-icon="inline-start" />Capturar localização atual</Button><p className="text-caption text-muted-foreground">{value ? "Localização capturada. Confirme o envio abaixo." : "O navegador solicitará permissão para acessar sua localização."}</p></>}
      {req.type === "SIGNATURE" && <><p className="text-label text-muted-foreground">Assine no espaço abaixo usando o dedo ou o mouse.</p><canvas ref={canvas} width={600} height={180} aria-label="Área para desenhar a assinatura" className="signature-pad" onPointerDown={e => { drawing.current = true; e.currentTarget.setPointerCapture(e.pointerId); const rect = e.currentTarget.getBoundingClientRect(), ctx = e.currentTarget.getContext("2d"); if (ctx) { ctx.beginPath(); ctx.moveTo((e.clientX - rect.left) * 600 / rect.width, (e.clientY - rect.top) * 180 / rect.height); } }} onPointerMove={e => { if (!drawing.current) return; const rect = e.currentTarget.getBoundingClientRect(), ctx = e.currentTarget.getContext("2d"); if (ctx) { ctx.lineWidth = 2; ctx.strokeStyle = "#1c2420"; ctx.lineTo((e.clientX - rect.left) * 600 / rect.width, (e.clientY - rect.top) * 180 / rect.height); ctx.stroke(); setSigned(true); } }} onPointerUp={() => { drawing.current = false; }} onPointerCancel={() => { drawing.current = false; }} /><Button type="button" variant="ghost" onClick={() => { canvas.current?.getContext("2d")?.clearRect(0, 0, 600, 180); setSigned(false); }}>Limpar assinatura</Button></>}
      <Button type="submit" variant="outline" disabled={busy || req.type === "LOCATION" && !value}>{busy ? <Spinner data-icon="inline-start" /> : <Send data-icon="inline-start" />}Enviar evidência</Button>
    </form>}
  </div>;
}

export function TaskDetailClient({ task }: TaskDetailClientProps) {
  const router = useRouter();
  const [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState(""), [dialog, setDialog] = useState<"pause" | "impediment" | null>(null), [reason, setReason] = useState(""), [category, setCategory] = useState("OUTROS");
  const terminal = ["COMPLETED", "CANCELLED", "NOT_COMPLETED"].includes(task.status), active = task.status === "IN_PROGRESS", scheduled = !!task.scheduledDate && new Date(task.scheduledDate) > new Date();
  async function run(action: () => Promise<{ error?: string }>, complete = false) { setBusy(true); setError(""); setNotice(""); try { const r = await action(); if (r.error) setError(r.error); else { setDialog(null); if (complete) router.push("/tasks"); router.refresh(); } } catch { setError("Não foi possível concluir a ação. Tente novamente."); } finally { setBusy(false); } }
  const evidencePending = task.evidenceRequirements.filter(r => r.required && r.submissions.filter(s => s.validationStatus === "VALID").length < r.minQuantity && r.submissions.filter(s => s.validationStatus === "REJECTED").length < 3).length;
  return <div className="page-stack employee-execution"><PageHeader title={task.title} subtitle={task.locationName || "Siga as orientações para realizar esta tarefa."} backHref="/tasks" actions={<StatusBadge status={scheduled ? "SCHEDULED" : task.status} />} />
    {task.correctionRequested && !terminal && <Alert><AlertDescription>Esta entrega está em uma nova rodada de correção. Registre novas evidências; os envios anteriores permanecem no histórico da gestão.</AlertDescription></Alert>}{error && <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}{notice && <Alert><AlertDescription>{notice}</AlertDescription></Alert>}
    <div className="employee-execution-grid"><div className="flex flex-col gap-5"><Card><CardHeader><CardTitle>1. Confira as orientações</CardTitle><CardDescription>Confira as instruções para executar e comprovar a entrega.</CardDescription></CardHeader><CardContent className="flex flex-col gap-4"><div className="flex flex-wrap gap-3 items-center"><PriorityBadge priority={task.priority} />{task.deadlineAt && <span className="text-label">Prazo: {new Date(task.deadlineAt).toLocaleString("pt-BR", { timeZone: "America/Sao_Paulo", dateStyle: "short", timeStyle: "short" })}</span>}</div>{task.description && <p>{task.description}</p>}<p className="whitespace-pre-wrap">{task.instructions || "Realize a atividade descrita no título e registre as evidências solicitadas abaixo."}</p>{task.dependencies.length > 0 && <div className="flex flex-col gap-2"><h3 className="font-semibold">Etapas relacionadas</h3>{task.dependencies.map(d => <div key={d.id} className="flex flex-wrap justify-between gap-2"><span>{d.dependsOnTask.title}</span><StatusBadge status={d.dependsOnTask.status} /></div>)}</div>}</CardContent></Card>
    <Card><CardHeader><CardTitle>2. Registre a entrega</CardTitle><CardDescription>{task.evidenceRequirements.length ? "Envie cada comprovação solicitada. Cancelar a escolha de um arquivo não conta como tentativa." : "Esta tarefa não exige evidências. Ao terminar o trabalho, selecione Concluir tarefa."}</CardDescription></CardHeader><CardContent className="flex flex-col gap-4">{task.evidenceRequirements.map(r => <EvidenceForm key={r.id} taskId={task.id} requirement={r} disabled={terminal || task.status === "BLOCKED"} onResult={message => { setError(message || ""); if (!message) setNotice("Evidência registrada."); router.refresh(); }} />)}</CardContent></Card>
    {!!task.occurrences.length && <Card><CardHeader><CardTitle>Ocorrências registradas</CardTitle></CardHeader><CardContent className="flex flex-col gap-3">{task.occurrences.map(o => <p key={o.id} className="text-label">{o.reason}</p>)}</CardContent></Card>}
    </div><Card className="employee-action-panel"><CardHeader><CardTitle>3. Próxima ação</CardTitle></CardHeader><CardContent className="flex flex-col gap-4">
      {scheduled ? <p>A tarefa será liberada em {new Date(task.scheduledDate!).toLocaleString("pt-BR", { timeZone: "America/Sao_Paulo", dateStyle: "short", timeStyle: "short" })}.</p> : task.status === "BLOCKED" ? <p>Aguarde as etapas anteriores. Esta tarefa será liberada quando as dependências forem atendidas; o SLA não corre enquanto estiver bloqueada.</p> : task.status === "PAUSED" ? <><p>O prazo continua sendo contado durante a pausa.</p><Button disabled={busy} onClick={() => run(() => resumeTaskAction(task.id))}><RotateCcw data-icon="inline-start" />Retomar tarefa</Button></> : !terminal && task.status !== "SUBMITTED" ? <><p>{task.status === "NEEDS_CORRECTION" ? "A gestão solicitou uma correção. Confira as orientações, anexe as novas evidências e finalize a conclusão." : evidencePending ? `${evidencePending} evidência(s) obrigatória(s) pendente(s). Registre antes de finalizar.` : "Tudo pronto para registrar a entrega."}</p><Button disabled={busy || !!evidencePending} onClick={() => run(() => completeTaskAction(task.id), true)}>{busy ? <Spinner data-icon="inline-start" /> : <Check data-icon="inline-start" />}{task.requiresApproval ? "Enviar para aprovação" : "Concluir tarefa"}</Button><Button variant="outline" disabled={busy} onClick={() => { setReason(""); setDialog("pause"); }}><Pause data-icon="inline-start" />Pausar tarefa</Button></> : task.status === "SUBMITTED" ? <p>Sua entrega foi enviada. Aguarde a revisão do aprovador; você será avisado se precisar corrigir algo.</p> : <p>Esta tarefa foi encerrada. As evidências e ocorrências permanecem no histórico.</p>}
      {!terminal && task.status !== "SUBMITTED" && <Button variant="ghost" disabled={busy} onClick={() => { setReason(""); setDialog("impediment"); }}>Não foi possível realizar</Button>}<Button variant="ghost" nativeButton={false} render={<Link href="/tasks" />}><ArrowLeft data-icon="inline-start" />Voltar às tarefas</Button>
    </CardContent></Card></div>
    {dialog && <Modal open title={dialog === "pause" ? "Pausar tarefa" : "Registrar impedimento"} onClose={() => { if (!busy) setDialog(null); }}><form className="flex flex-col gap-5" onSubmit={e => { e.preventDefault(); run(() => dialog === "pause" ? pauseTaskAction(task.id, category, reason) : reportImpedimentAction(task.id, category, reason)); }}><p>{dialog === "pause" ? "O prazo continua correndo. Registre o motivo para a gestão acompanhar." : "Use quando uma condição da operação impedir a realização. Isso encerra a tarefa como não realizada e avisa a gestão."}</p><FieldGroup><Field><FieldLabel htmlFor="reason-category">Motivo</FieldLabel><NativeSelect id="reason-category" className="w-full" value={category} onChange={e => setCategory(e.target.value)}>{Object.entries({ OUTROS: "Outro motivo", MATERIAL_FALTANTE: "Falta de material", EQUIPAMENTO_QUEBRADO: "Equipamento com defeito", ACESSO_BLOQUEADO: "Local sem acesso", INTERVALO: "Intervalo" }).map(([v, l]) => <NativeSelectOption key={v} value={v}>{l}</NativeSelectOption>)}</NativeSelect></Field><Field><FieldLabel htmlFor="reason-detail">O que aconteceu?</FieldLabel><Textarea id="reason-detail" required minLength={3} maxLength={1000} value={reason} onChange={e => setReason(e.target.value)} /></Field></FieldGroup>{error && <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" disabled={busy} onClick={() => setDialog(null)}>Voltar</Button><Button disabled={busy} type="submit">{busy && <Spinner data-icon="inline-start" />}{dialog === "pause" ? "Confirmar pausa" : "Registrar impedimento"}</Button></div></form></Modal>}
  </div>;
}
