const labels: Record<string, string> = {
  OWNER: "Proprietário",
  ADMIN: "Administrador",
  MANAGER: "Gestor",
  EMPLOYEE: "Colaborador",
  SUPERADMIN: "Superadministrador",
  LOW: "Baixa",
  MEDIUM: "Média",
  HIGH: "Alta",
  CRITICAL: "Crítica",
  PROCESS: "Processo",
  AD_HOC: "Tarefa avulsa",
  SCHEDULED: "Programada",
  AVAILABLE: "Disponível",
  IN_PROGRESS: "Em andamento",
  PAUSED: "Pausada",
  BLOCKED: "Bloqueada",
  SUBMITTED: "Em revisão",
  PENDING_REVIEW: "Aguardando aprovação",
  NEEDS_CORRECTION: "Correção solicitada",
  COMPLETED: "Concluída",
  CANCELLED: "Cancelada",
  NOT_COMPLETED: "Impedimento",
  PENDING: "Pendente",
  APPROVED: "Aprovada",
  REJECTED: "Rejeitada",
  BLOCKING: "Bloqueante",
  INFORMATIVE: "Informativa",
  APPROVAL_CONDITION: "Condição de aprovação",
  TASK_CREATED: "Tarefa criada",
  TASK_STARTED: "Tarefa iniciada",
  TASK_COMPLETED: "Tarefa concluída",
  TASK_TRANSFERRED: "Responsável alterado",
  TASK_CLAIMED: "Tarefa assumida",
  TASK_PAUSED: "Tarefa pausada",
  TASK_RESUMED: "Tarefa retomada",
  TASK_IMPEDIMENT_REPORTED: "Impedimento registrado",
  TASK_CANCELLED: "Tarefa cancelada",
  TASK_TRASHED: "Tarefa enviada à lixeira",
  TASK_RESTORED: "Tarefa restaurada",
  TASK_PURGED: "Tarefa excluída definitivamente",
  EVIDENCE_SUBMITTED: "Evidência enviada",
  EVIDENCE_VALIDATION_FAILED: "Evidência recusada",
  APPROVAL_APPROVED: "Etapa aprovada",
  APPROVAL_REJECTED: "Etapa rejeitada",
  MEMBER_INVITED: "Pessoa convidada",
  MEMBER_PIN_RESET: "PIN redefinido",
  MEMBER_STATUS_ACTIVE: "Acesso ativado",
  MEMBER_STATUS_INACTIVE: "Acesso desativado",
  MEMBER_STATUS_SUSPENDED: "Acesso suspenso",
  MEMBER_STATUS_INVITED: "Convite enviado",
  LOCATION_CREATED: "Unidade criada",
  TEAM_CREATED: "Equipe criada",
  ORGANIZATION_SETTINGS_UPDATED: "Configurações atualizadas",
  ORGANIZATION_ACTIVATED: "Organização ativada",
  ORGANIZATION_SUSPENDED: "Organização suspensa",
  PROCESS_CREATED: "Processo criado",
  PROCESS_STATUS_ACTIVE: "Processo ativado",
  PROCESS_STATUS_PAUSED: "Processo pausado",
  PROCESS_STATUS_ARCHIVED: "Processo arquivado",
  EXECUTION_GENERATED: "Execução criada",
  EXECUTION_REOPENED: "Execução reaberta",
};

export function uiLabel(value: string) {
  return labels[value] ?? value.replaceAll("_", " ").toLocaleLowerCase("pt-BR");
}
